### PR TITLE
Reduce in-memory cache size from 2Mb to 500Kb

### PR DESCRIPTION
**Pull request by monich**
Over 100 background processes load libsqlite3.so on the jolla phone. Those which actually perform SQL queries and keep the database open will eventually allocate all 2MB of heap per database (yes, per database) for the sqlite in-memory cache. That's potentially hundreds of megabytes of heap, which I think is too much for a device with 1GB of RAM.

Those processes which actually need 2MB of cache can increase it using the PRAGMA cache_size command.

### CODE REVIEW

**Comment by rburchell** [comment]
Might also want to make sure QtSql is using the system-based sqlite, otherwise it won't be getting the benefit of this.

**Comment by monich** [comment]
My sample QtSql app was using the system-based sqlite, so I assume all other apps are using it as well.

**Comment by monich** [comment]
@chriadam @VDVsx @amtep @matthewvogt Please check if sqlite cache size needs to be increased in your components

**Comment by amtep** [comment]
Smaller cache is ok for Notes.

Not sure about qtcontacts-sqlite. What are the symptoms of a too-small cache?

**Comment by matthewvogt** [comment]
Presumably the only symptom would be slower queries once the cache is filled.  A comparison of runtimes using 'fetchtimes -q' from qtcontacts-sqlite-qt5 would give a reasonable indication if the slow down is significant.

**Pull request merged**
