### PR TITLE
Update to sqlite 3.8.11

### PR DESCRIPTION
**Pull request by rojkov**
Gecko38 depends on sqlite >= 3.8.9

### CODE REVIEW

**Comment by rainemak** [comment]
Bump up also spec file Version field. @chriadam would this be ok for you?

**Comment by chriadam** [comment]
Should be fine, although I'd like @matthewvogt to confirm.

**Comment by rojkov** [comment]
Version set to 3.8.11

**Comment by matthewvogt** [comment]
LGTM.  Is there any particular reason why we're going to 3.8.11 rather than 3.8.11.1?

For what it's worth, here is the relevant changelog:

2015-07-29 (3.8.11.1)

    Restore an undocumented side-effect of PRAGMA cache_size: force the database schema to be parsed if the database has not been previously accessed.
    Fix a long-standing problem in sqlite3_changes() for WITHOUT ROWID tables that was reported a few hours after the 3.8.11 release.
    SQLITE_SOURCE_ID: "2015-07-29 20:00:57 cf538e2783e468bbc25e7cb2a9ee64d3e0e80b2f"
    SHA1 for sqlite3.c: 3be71d99121fe5b17f057011025bcf84e7cc6c84 

2015-07-27 (3.8.11)

    Added the experimental RBU extension. Note that this extension is experimental and subject to change in incompatible ways.
    Added the experimental FTS5 extension. Note that this extension is experimental and subject to change in incompatible ways.
    Added the sqlite3_value_dup() and sqlite3_value_free() interfaces.
    Enhance the spellfix1 extension to support ON CONFLICT clauses.
    The IS operator is now able to drive indexes.
    Enhance the query planner to permit automatic indexing on FROM-clause subqueries that are implemented by co-routine.
    Disallow the use of "rowid" in common table expressions.
    Added the PRAGMA cell_size_check command for better and earlier detection of database file corruption.
    Added the matchinfo 'b' flag to the matchinfo() function in FTS3.
    Improved fuzz-testing of database files, with fixes for problems found.
    Add the fuzzcheck test program and automatically run this program using both SQL and database test cases on "make test".
    Added the SQLITE_MUTEX_STATIC_VFS1 static mutex and use it in the Windows VFS.
    The sqlite3_profile() callback is invoked (by sqlite3_reset() or sqlite3_finalize()) for statements that did not run to completion.
    Enhance the page cache so that it can preallocate a block of memory to use for the initial set page cache lines. Set the default preallocation to 100 pages. Yields about a 5% performance increase on common workloads.
    Miscellaneous micro-optimizations result in 22.3% more work for the same number of CPU cycles relative to the previous release. SQLite now runs twice as fast as version 3.8.0 and three times as fast as version 3.3.9. (Measured using cachegrind on the speedtest1.c workload on Ubuntu 14.04 x64 with gcc 4.8.2 and -Os. Your performance may vary.)
    Added the sqlite3_result_zeroblob64() and sqlite3_bind_zeroblob64() interfaces.

    Important bug fixes:
    Fix CREATE TABLE AS so that columns of type TEXT never end up holding an INT value. Ticket f2ad7de056ab1dc9200
    Fix CREATE TABLE AS so that it does not leave NULL entries in the sqlite_master table if the SELECT statement on the right-hand side aborts with an error. Ticket 873cae2b6e25b
    Fix the skip-scan optimization so that it works correctly when the OR optimization is used on WITHOUT ROWID tables. Ticket 8fd39115d8f46
    Fix the sqlite3_memory_used() and sqlite3_memory_highwater() interfaces so that they actually do provide a 64-bit answer.

    Hashes:
    SQLITE_SOURCE_ID: "2015-07-27 13:49:41 b8e92227a469de677a66da62e4361f099c0b79d0"
    SHA1 for sqlite3.c: 719f6891abcd9c459b5460b191d731cd12a3643e 

2015-05-20 (3.8.10.2)

    Fix an index corruption issue introduced by version 3.8.7. An index with a TEXT key can be corrupted by an INSERT into the corresponding table if the table has two nested triggers that convert the key value to INTEGER and back to TEXT again. Ticket 34cd55d68e0
    SQLITE_SOURCE_ID: "2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4"
    SHA1 for sqlite3.c: 638abb77965332c956dbbd2c8e4248e84da4eb63 

2015-05-09 (3.8.10.1)

    Make sqlite3_compileoption_used() responsive to the SQLITE_ENABLE_DBSTAT_VTAB compile-time option.
    Fix a harmless warning in the command-line shell on some versions of MSVC.
    Fix minor issues with the dbstat virtual table.
    SQLITE_SOURCE_ID: "2015-05-09 12:14:55 05b4b1f2a937c06c90db70c09890038f6c98ec40"
    SHA1 for sqlite3.c: 85e4e1c08c7df28ef61bb9759a0d466e0eefbaa2 

2015-05-07 (3.8.10)

    Added the sqldiff.exe utility program for computing the differences between two SQLite database files.
    Added the matchinfo y flag to the matchinfo() function of FTS3.
    Performance improvements for ORDER BY, VACUUM, CREATE INDEX, PRAGMA integrity_check, and PRAGMA quick_check.
    Fix many obscure problems discovered while SQL fuzzing.
    Identify all methods for important objects in the interface documentation. (example)
    Made the American Fuzzy Lop fuzzer a standard part of SQLite's testing strategy.
    Add the ".binary" and ".limits" commands to the command-line shell.
    Make the dbstat virtual table part of standard builds when compiled with the SQLITE_ENABLE_DBSTAT_VTAB option.
    SQLITE_SOURCE_ID: "2015-05-07 11:53:08 cf975957b9ae671f34bb65f049acf351e650d437"
    SHA1 for sqlite3.c: 0b34f0de356a3f21b9dfc761f3b7821b6353c570 

2015-04-08 (3.8.9)

    Add VxWorks-7 as an officially supported and tested platform.
    Added the sqlite3_status64() interface.
    Fix memory size tracking so that it works even if SQLite uses more than 2GiB of memory.
    Added the PRAGMA index_xinfo command.
    Fix a potential 32-bit integer overflow problem in the sqlite3_blob_read() and sqlite3_blob_write() interfaces.
    Ensure that prepared statements automatically reset on extended error codes of SQLITE_BUSY and SQLITE_LOCKED even when compiled using SQLITE_OMIT_AUTORESET.
    Correct miscounts in the sqlite3_analyzer.exe utility related to WITHOUT ROWID tables.
    Added the ".dbinfo" command to the command-line shell.
    Improve the performance of fts3/4 queries that use the OR operator and at least one auxiliary fts function.
    Fix a bug in the fts3 snippet() function causing it to omit leading separator characters from snippets that begin with the first token in a column.
    SQLITE_SOURCE_ID: "2015-04-08 12:16:33 8a8ffc862e96f57aa698f93de10dee28e69f6e09"
    SHA1 for sqlite3.c: 49f1c3ae347e1327b5aaa6c7f76126bdf09c6f42 

2015-02-25 (3.8.8.3)

    Fix a bug (ticket 2326c258d02ead33) that can lead to incorrect results if the qualifying constraint of a partial index appears in the ON clause of a LEFT JOIN.
    Added the ability to link against the "linenoise" command-line editing library in unix builds of the command-line shell.
    SQLITE_SOURCE_ID: "2015-02-25 13:29:11 9d6c1880fb75660bbabd693175579529785f8a6b"
    SHA1 for sqlite3.c: 74ee38c8c6fd175ec85a47276dfcefe8a262827a 

2015-01-30 (3.8.8.2)

    Enhance sqlite3_wal_checkpoint_v2(TRUNCATE) interface so that it truncates the WAL file even if there is no checkpoint work to be done.
    SQLITE_SOURCE_ID: "2015-01-30 14:30:45 7757fc721220e136620a89c9d28247f28bbbc098"
    SHA1 for sqlite3.c: 85ce79948116aa9a087ec345c9d2ce2c1d3cd8af 

2015-01-20 (3.8.8.1)

    Fix a bug in the sorting logic, present since version 3.8.4, that can cause output to appear in the wrong order on queries that contains an ORDER BY clause, a LIMIT clause, and that have approximately 60 or more columns in the result set. Ticket f97c4637102a3ae72b79.
    SQLITE_SOURCE_ID: "2015-01-20 16:51:25 f73337e3e289915a76ca96e7a05a1a8d4e890d55"
    SHA1 for sqlite3.c: 33987fb50dcc09f1429a653d6b47672f5a96f19e 

2015-01-16 (3.8.8)

    New Features:
    Added the PRAGMA data_version command that can be used to determine if a database file has been modified by another process.
    Added the SQLITE_CHECKPOINT_TRUNCATE option to the sqlite3_wal_checkpoint_v2() interface, with corresponding enhancements to PRAGMA wal_checkpoint.
    Added the sqlite3_stmt_scanstatus() interface, available only when compiled with SQLITE_ENABLE_STMT_SCANSTATUS.
    The sqlite3_table_column_metadata() is enhanced to work correctly on WITHOUT ROWID tables and to check for the existence of a a table if the column name parameter is NULL. The interface is now also included in the build by default, without requiring the SQLITE_ENABLE_COLUMN_METADATA compile-time option.
    Added the SQLITE_ENABLE_API_ARMOR compile-time option.
    Added the SQLITE_REVERSE_UNORDERED_SELECTS compile-time option.
    Added the SQLITE_SORTER_PMASZ compile-time option and SQLITE_CONFIG_PMASZ start-time option.
    Added the SQLITE_CONFIG_PCACHE_HDRSZ option to sqlite3_config() which makes it easier for applications to determine the appropriate amount of memory for use with SQLITE_CONFIG_PAGECACHE.
    The number of rows in a VALUES clause is no longer limited by SQLITE_LIMIT_COMPOUND_SELECT.
    Added the eval.c loadable extension that implements an eval() SQL function that will recursively evaluate SQL.

    Performance Enhancements:
    Reduce the number of memcpy() operations involved in balancing a b-tree, for 3.2% overall performance boost.
    Improvements to cost estimates for the skip-scan optimization.
    The automatic indexing optimization is now capable of generating a partial index if that is appropriate.

    Bug fixes:
    Ensure durability following a power loss with "PRAGMA journal_mode=TRUNCATE" by calling fsync() right after truncating the journal file.
    The query planner now recognizes that any column in the right-hand table of a LEFT JOIN can be NULL, even if that column has a NOT NULL constraint. Avoid trying to optimize out NULL tests in those cases. Fix for ticket 6f2222d550f5b0ee7ed.
    Make sure ORDER BY puts rows in ascending order even if the DISTINCT operator is implemented using a descending index. Fix for ticket c5ea805691bfc4204b1cb9e.
    Fix data races that might occur under stress when running with many threads in shared cache mode where some of the threads are opening and closing connections.
    Fix obscure crash bugs found by american fuzzy lop. Ticket a59ae93ee990a55.
    Work around a GCC optimizer bug (for gcc 4.2.1 on MacOS 10.7) that caused the R-Tree extension to compute incorrect results when compiled with -O3.

    Other changes:
    Disable the use of the strchrnul() C-library routine unless it is specifically enabled using the -DHAVE_STRCHRNULL compile-time option.
    Improvements to the effectiveness and accuracy of the likelihood(), likely(), and unlikely() SQL hint functions.
    SQLITE_SOURCE_ID: "2015-01-16 12:08:06 7d68a42face3ab14ed88407d4331872f5b243fdf"
    SHA1 for sqlite3.c: 91aea4cc722371d58aae3d22e94d2a4165276905 

2014-12-09 (3.8.7.4)

    Bug fix: Add in a mutex that was omitted from the previous release.
    SQLITE_SOURCE_ID: "2014-12-09 01:34:36 f66f7a17b78ba617acde90fc810107f34f1a1f2e"
    SHA1 for sqlite3.c: 0a56693a3c24aa3217098afab1b6fecccdedfd23 

2014-12-06 (3.8.7.3)

    Bug fix: Ensure the cached KeyInfo objects (an internal abstraction not visible to the application) do not go stale when operating in shared cache mode and frequently closing and reopening some database connections while leaving other database connections on the same shared cache open continuously. Ticket e4a18565a36884b00edf.
    Bug fix: Recognize that any column in the right-hand table of a LEFT JOIN can be NULL even if the column has a NOT NULL constraint. Do not apply optimizations that assume the column is never NULL. Ticket 6f2222d550f5b0ee7ed.
    SQLITE_SOURCE_ID: "2014-12-05 22:29:24 647e77e853e81a5effeb4c33477910400a67ba86"
    SHA1 for sqlite3.c: 3ad2f5ba3a4a3e3e51a1dac9fda9224b359f0261 

2014-11-19 (3.8.7.2)

    Enhance the ROLLBACK command so that pending queries are allowed to continue as long as the schema is unchanged. Formerly, a ROLLBACK would cause all pending queries to fail with an SQLITE_ABORT or SQLITE_ABORT_ROLLBACK error. That error is still returned if the ROLLBACK modifies the schema.
    Bug fix: Make sure that NULL results from OP_Column are fully and completely NULL and do not have the MEM_Ephem bit set. Ticket 094d39a4c95ee4.
    Bug fix: The %c format in sqlite3_mprintf() is able to handle precisions greater than 70.
    Bug fix: Do not automatically remove the DISTINCT keyword from a SELECT that forms the right-hand side of an IN operator since it is necessary if the SELECT also contains a LIMIT. Ticket db87229497.
    SQLITE_SOURCE_ID: "2014-11-18 20:57:56 2ab564bf9655b7c7b97ab85cafc8a48329b27f93"
    SHA1 for sqlite3.c: b2a68d5783f48dba6a8cb50d8bf69b238c5ec53a 

2014-10-30 (3.8.7.1)

    In PRAGMA journal_mode=TRUNCATE mode, call fsync() immediately after truncating the journal file to ensure that the transaction is durable across a power loss.
    Fix an assertion fault that can occur when updating the NULL value of a field at the end of a table that was added using ALTER TABLE ADD COLUMN.
    Do not attempt to use the strchrnul() function from the standard C library unless the HAVE_STRCHRNULL compile-time option is set.
    Fix a couple of problems associated with running an UPDATE or DELETE on a VIEW with a rowid in the WHERE clause.
    SQLITE_SOURCE_ID: "2014-10-29 13:59:56 3b7b72c4685aa5cf5e675c2c47ebec10d9704221"
    SHA1 for sqlite3.c: 2d25bd1a73dc40f538f3a81c28e6efa5999bdf0c 

2014-10-17 (3.8.7)

    Performance Enhancements:
    Many micro-optimizations result in 20.3% more work for the same number of CPU cycles relative to the previous release. The cumulative performance increase since version 3.8.0 is 61%. (Measured using cachegrind on the speedtest1.c workload on Ubuntu 13.10 x64 with gcc 4.8.1 and -Os. Your performance may vary.)
    The sorter can use auxiliary helper threads to increase real-time response. This feature is off by default and may be enabled using the PRAGMA threads command or the SQLITE_DEFAULT_WORKER_THREADS compile-time option.
    Enhance the skip-scan optimization so that it is able to skip index terms that occur in the middle of the index, not just as the left-hand side of the index.
    Improved optimization of CAST operators.
    Various improvements in how the query planner uses sqlite_stat4 information to estimate plan costs.

    New Features:
    Added new interfaces with 64-bit length parameters: sqlite3_malloc64(), sqlite3_realloc64(), sqlite3_bind_blob64(), sqlite3_result_blob64(), sqlite3_bind_text64(), and sqlite3_result_text64().
    Added the new interface sqlite3_msize() that returns the size of a memory allocation obtained from sqlite3_malloc64() and its variants.
    Added the SQLITE_LIMIT_WORKER_THREADS option to sqlite3_limit() and PRAGMA threads command for configuring the number of available worker threads.
    The spellfix1 extension allows the application to optionally specify the rowid for each INSERT.
    Added the User Authentication extension.

    Bug Fixes:
    Fix a bug in the partial index implementation that might result in an incorrect answer if a partial index is used in a subquery or in a view. Ticket 98d973b8f5.
    Fix a query planner bug that might cause a table to be scanned in the wrong direction (thus reversing the order of output) when a DESC index is used to implement the ORDER BY clause on a query that has an identical GROUP BY clause. Ticket ba7cbfaedc7e6.
    Fix a bug in sqlite3_trace() that was causing it to sometimes fail to print an SQL statement if that statement needed to be re-prepared. Ticket 11d5aa455e0d98f3c1e6a08
    Fix a faulty assert() statement. Ticket 369d57fb8e5ccdff06f1

    Test, Debug, and Analysis Changes:
    Show ASCII-art abstract syntax tree diagrams using the ".selecttrace" and ".wheretrace" commands in the command-line shell when compiled with SQLITE_DEBUG, SQLITE_ENABLE_SELECTTRACE, and SQLITE_ENABLE_WHERETRACE. Also provide the sqlite3TreeViewExpr() and sqlite3TreeViewSelect() entry points that can be invoked from with the debugger to show the parse tree when stopped at a breakpoint.
    Drop support for SQLITE_ENABLE_TREE_EXPLAIN. The SELECTTRACE mechanism provides more useful diagnostics information.
    New options to the command-line shell for configuring auxiliary memory usage: --pagecache, --lookaside, and --scratch.
    SQLITE_SOURCE_ID: "2014-10-17 11:24:17 e4ab094f8afce0817f4074e823fabe59fc29ebb4"
    SHA1 for sqlite3.c: 56dcf5e931a9e1fa12fc2d600cd91d3bf9b639cd 

2014-08-15 (3.8.6)

    Added support for hexadecimal integer literals in the SQL parser. (Ex: 0x123abc)
    Enhanced the PRAGMA integrity_check command to detect UNIQUE and NOT NULL constraint violations.
    Increase the maximum value of SQLITE_MAX_ATTACHED from 62 to 125.
    Increase the timeout in WAL mode before issuing an SQLITE_PROTOCOL error from 1 second to 10 seconds.
    Added the likely(X) SQL function.
    The unicode61 tokenizer is now included in FTS4 by default.
    Trigger automatic reprepares on all prepared statements when ANALYZE is run.
    Added a new loadable extension source code file to the source tree: fileio.c
    Add extension functions readfile(X) and writefile(X,Y) (using code copy/pasted from fileio.c in the previous bullet) to the command-line shell.
    Added the .fullschema dot-command to the command-line shell.

    Performance Enhancements:
    Deactivate the DISTINCT keyword on subqueries on the right-hand side of the IN operator.
    Add the capability of evaluating an IN operator as a sequence of comparisons as an alternative to using a table lookup. Use the sequence of comparisons implementation in circumstances where it is likely to be faster, such as when the right-hand side of the IN operator is small and/or changes frequently.
    The query planner now uses sqlite_stat4 information (created by ANALYZE) to help determine if the skip-scan optimization is appropriate.
    Ensure that the query planner never tries to use a self-made transient index in place of a schema-defined index.
    Other minor tweaks to improve the quality of VDBE code.

    Bug Fixes:
    Fix a bug in CREATE UNIQUE INDEX, introduced when WITHOUT ROWID support added in version 3.8.2, that allows a non-unique NOT NULL column to be given a UNIQUE index. Ticket 9a6daf340df99ba93c
    Fix a bug in R-Tree extension, introduced in the previous release, that can cause an incorrect results for queries that use the rowid of the R-Tree on the left-hand side of an IN operator. Ticket d2889096e7bdeac6.
    Fix the sqlite3_stmt_busy() interface so that it gives the correct answer for ROLLBACK statements that have been stepped but never reset.
    Fix a bug in that would cause a null pointer to be dereferenced if a column with a DEFAULT that is an aggregate function tried to usee its DEFAULT. Ticket 3a88d85f36704eebe1
    CSV output from the command-line shell now always uses CRNL for the row separator and avoids inserting CR in front of NLs contained in data.
    Fix a column affinity problem with the IN operator. Ticket 9a8b09f8e6.
    Fix the ANALYZE command so that it adds correct samples for WITHOUT ROWID tables in the sqlite_stat4 table. Ticket b2fa5424e6fcb15.
    SQLITE_SOURCE_ID: "2014-08-15 11:46:33 9491ba7d738528f168657adb43a198238abde19e"
    SHA1 for sqlite3.c: 72c64f05cd9babb9c0f9b3c82536d83be7804b1c 

2014-06-04 (3.8.5)

    Added support for partial sorting by index.
    Enhance the query planner so that it always prefers an index that uses a superset of WHERE clause terms relative to some other index.
    Improvements to the automerge command of FTS4 to better control the index size for a full-text index that is subject to a large number of updates.
    Added the sqlite3_rtree_query_callback() interface to R-Tree extension
    Added new URI query parameters "nolock" and "immutable".
    Use less memory by not remembering CHECK constraints on read-only database connections.
    Enable the OR optimization for WITHOUT ROWID tables.
    Render expressions of the form "x IN (?)" (with a single value in the list on the right-hand side of the IN operator) as if they where "x==?", Similarly optimize "x NOT IN (?)"
    Add the ".system" and ".once" commands to the command-line shell.
    Added the SQLITE_IOCAP_IMMUTABLE bit to the set of bits that can be returned by the xDeviceCharacteristics method of a VFS.
    Added the SQLITE_TESTCTRL_BYTEORDER test control.

    Bug Fixes:
    OFFSET clause ignored on queries without a FROM clause. Ticket 07d6a0453d
    Assertion fault on queries involving expressions of the form "x IN (?)". Ticket e39d032577.
    Incorrect column datatype reported. Ticket a8a0d2996a
    Duplicate row returned on a query against a table with more than 16 indices, each on a separate column, and all used via OR-connected constraints. Ticket 10fb063b11
    Partial index causes assertion fault on UPDATE OR REPLACE. Ticket 2ea3e9fe63
    Crash when calling undocumented SQL function sqlite_rename_parent() with NULL parameters. Ticket 264b970c43
    ORDER BY ignored if the query has an identical GROUP BY. Ticket b75a9ca6b0
    The group_concat(x,'') SQL function returns NULL instead of an empty string when all inputs are empty strings. Ticket 55746f9e65
    Fix a bug in the VDBE code generator that caused crashes when doing an INSERT INTO ... SELECT statement where the number of columns being inserted is larger than the number of columns in the destination table. Ticket e9654505cfd
    Fix a problem in CSV import in the command-line shell where if the leftmost field of the first row in the CSV file was both zero bytes in size and unquoted no data would be imported.
    Fix a problem in FTS4 where the left-most column that contained the notindexed column name as a prefix was not indexed rather than the column whose name matched exactly.
    Fix the sqlite3_db_readonly() interface so that it returns true if the database is read-only due to the file format write version number being too large.
    SQLITE_SOURCE_ID: "2014-06-04 14:06:34 b1ed4f2a34ba66c29b130f8d13e9092758019212"
    SHA1 for sqlite3.c: 7bc194957238c61b1a47f301270286be5bc5208c 

2014-04-03 (3.8.4.3)

    Add a one-character fix for a problem that might cause incorrect query results on a query that mixes DISTINCT, GROUP BY in a subquery, and ORDER BY. Ticket 98825a79ce14.
    SQLITE_SOURCE_ID: "2014-04-03 16:53:12 a611fa96c4a848614efe899130359c9f6fb889c3"
    SHA1 for sqlite3.c: 310a1faeb9332a3cd8d1f53b4a2e055abf537bdc 

2014-03-26 (3.8.4.2)

    Fix a potential buffer overread that could result when trying to search a corrupt database file.
    SQLITE_SOURCE_ID: "2014-03-26 18:51:19 02ea166372bdb2ef9d8dfbb05e78a97609673a8e"
    SHA1 for sqlite3.c: 4685ca86c2ea0649ed9f59a500013e90b3fe6d03

**Comment by rojkov** [comment]
No, no reason other than the fact the PR had been prepared before 3.8.11.1 was released.

**Comment by rainemak** [comment]
LGTM

**Comment by rainemak** [comment]
PR https://git.merproject.org/mer-core/sqlite/merge_requests/2 obsoletes this one.

**Pull request closed without merging**
